// client
export const LOG_IN = 'LOG_IN'
export const CLICK_LOG_OUT = 'CLICK_LOG_OUT'
export const LOG_OUT = 'LOG_OUT'
export const FETCH_LOGIN_STATE = 'FETCH_LOGIN_STATE'
export const FAIL_FETCHING_LOGIN_STATE = 'FAIL_FETCH_LOGIN_STATE'
export const FETCH_USER = 'FETCH_USER'
export const FAIL_FETCHING_USER = 'FAIL_FETCHING_USER'
export const SIGN_UP = 'SIGN_UP'
export const PASSWORD_ERROR = 'PASSWORD_ERROR'
export const FETCH_FRIEND = 'FETCH_FRIEND'
export const UPDATE_FRIEND = 'UPDATE_FRIEND'

// user
export const SEARCH_USER = 'SEARCH_USER'
export const FETCH_SEARCH_USER = 'FETCH_SEARCH_USER'
export const UPDATE_SEARCHED_USER = 'UPDATE_SEARCHED_USER'
export const FRIEND_REQUEST = 'FRIEND_REQUEST'
export const UPDATE_FRIEND_REQUEST = 'UPDATE_FRIEND_REQUEST'

// village
export const FETCH_VILLAGE = 'FETCH_VILLAGE'
export const ENTER_VILLAGE = 'ENTER_VILLAGE'
